#!/usr/bin/env node

const args = require('minimist')(process.argv.slice(2));
const buildFromTemplate = require('./buildFromTemplate');
const appendToFile = require('./appendToFile'); 

const actionName = args.name;

if (!actionName) {
    console.error('Action name not provided. Please use a "--name" argument.');
    return;
}

const templateValues = buildFromTemplate(actionName, 'newAction.tmpl', 'js/actions');

const newLine = `export { ${templateValues.name}, ${templateValues.nameCaps} } from './${templateValues.camelCase}';`;

appendToFile('js/actions/index.js', newLine);
