#!/usr/bin/env node

const _ = require('lodash');
const buildFromTemplate = require('./buildFromTemplate');

const componentName = _.get(process.argv, '2');

const isForm = Boolean(_.get(process.argv, '3', false));

buildFromTemplate('index', isForm ? 'newFormComponent.tmpl' : 'newComponent.tmpl', `js/components/${componentName}`);