#!/usr/bin/env node

const args = require('minimist')(process.argv.slice(2));
const buildFromTemplate = require('./buildFromTemplate');
const addLinesAround = require('./addLinesAround');

const reducerName = args.name;

if (!reducerName) {
    console.error('Reducer name not provided. Please use a "--name" argument.');
    return;
}

const templateValues = buildFromTemplate(reducerName, 'newReducer.tmpl', 'js/reducers');

const importLine = `import ${templateValues.name}Reducer from './${ templateValues.camelCase}';\n`;
const expectedLine = 'const rootReducer = combineReducers({';
const addReducerLine = `    ${templateValues.camelCase}: ${templateValues.name}Reducer,`;


addLinesAround('js/reducers/index.js', expectedLine, importLine, addReducerLine);