#!/usr/bin/env node

const args = require('minimist')(process.argv.slice(2));
const buildFromTemplate = require('./buildFromTemplate');

const componentName = args.name;

if (!componentName) {
    console.error('Component name not provided. Please use a "--name" argument.');
    return;
}

const isForm = args.form === 'true';

buildFromTemplate('index', isForm ? 'newFormComponent.tmpl' : 'newComponent.tmpl', `js/components/${componentName}`);